stages:
- name: 编译
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: eureka.jar
- name: prod
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
